version: '3.9'

services:
  postgres:
    image: postgres
    container_name: dummy-postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER : suhas
      POSTGRES_PASSWORD: secrete123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local